#!/bin/bash
# This hook is run after this virtualenv is activated.

export PYTHONPATH=$WORKON_HOME/gol/src/gol
export PYTHONPATH=$WORKON_HOME/gol/src:$PYTHONPATH
export PYTHONPATH=$WORKON_HOME/gol/src/contrib/PyGLy:$PYTHONPATH
export PYTHONPATH=$WORKON_HOME/gol/src/contrib/Pyrr:$PYTHONPATH
